# Photoshop style by Derydoca from ImThemes
alpha = 1.0
disabledAlpha = 0.6000000238418579
windowPadding = [8.0, 8.0]
windowRounding = 4.0
windowBorderSize = 1.0
windowMinSize = [32.0, 32.0]
windowTitleAlign = [0.0, 0.5]
windowMenuButtonPosition = "Left"
childRounding = 4.0
childBorderSize = 1.0
popupRounding = 2.0
popupBorderSize = 1.0
framePadding = [4.0, 3.0]
frameRounding = 2.0
frameBorderSize = 1.0
itemSpacing = [8.0, 4.0]
itemInnerSpacing = [4.0, 4.0]
cellPadding = [4.0, 2.0]
indentSpacing = 21.0
columnsMinSpacing = 6.0
scrollbarSize = 13.0
scrollbarRounding = 12.0
grabMinSize = 7.0
grabRounding = 0.0
tabRounding = 0.0
tabBorderSize = 1.0
tabMinWidthForCloseButton = 0.0
colorButtonPosition = "Right"
buttonTextAlign = [0.5, 0.5]
selectableTextAlign = [0.0, 0.0]

[colors]
Text = "rgba(255, 255, 255, 1.0)"
TextDisabled = "rgba(127, 127, 127, 1.0)"
WindowBg = "rgba(45, 45, 45, 1.0)"
ChildBg = "rgba(71, 71, 71, 0.0)"
PopupBg = "rgba(79, 79, 79, 1.0)"
Border = "rgba(67, 67, 67, 1.0)"
BorderShadow = "rgba(0, 0, 0, 0.0)"
FrameBg = "rgba(40, 40, 40, 1.0)"
FrameBgHovered = "rgba(51, 51, 51, 1.0)"
FrameBgActive = "rgba(71, 71, 71, 1.0)"
TitleBg = "rgba(37, 37, 37, 1.0)"
TitleBgActive = "rgba(37, 37, 37, 1.0)"
TitleBgCollapsed = "rgba(37, 37, 37, 1.0)"
MenuBarBg = "rgba(49, 49, 49, 1.0)"
ScrollbarBg = "rgba(40, 40, 40, 1.0)"
ScrollbarGrab = "rgba(70, 70, 70, 1.0)"
ScrollbarGrabHovered = "rgba(76, 76, 76, 1.0)"
ScrollbarGrabActive = "rgba(255, 99, 0, 1.0)"
CheckMark = "rgba(255, 255, 255, 1.0)"
SliderGrab = "rgba(99, 99, 99, 1.0)"
SliderGrabActive = "rgba(255, 99, 0, 1.0)"
Button = "rgba(255, 255, 255, 0.0)"
ButtonHovered = "rgba(255, 255, 255, 0.1560000032186508)"
ButtonActive = "rgba(255, 255, 255, 0.3910000026226044)"
Header = "rgba(79, 79, 79, 1.0)"
HeaderHovered = "rgba(119, 119, 119, 1.0)"
HeaderActive = "rgba(119, 119, 119, 1.0)"
Separator = "rgba(67, 67, 67, 1.0)"
SeparatorHovered = "rgba(99, 99, 99, 1.0)"
SeparatorActive = "rgba(255, 99, 0, 1.0)"
ResizeGrip = "rgba(255, 255, 255, 0.25)"
ResizeGripHovered = "rgba(255, 255, 255, 0.6700000166893005)"
ResizeGripActive = "rgba(255, 99, 0, 1.0)"
Tab = "rgba(24, 24, 24, 1.0)"
TabHovered = "rgba(89, 89, 89, 1.0)"
TabActive = "rgba(49, 49, 49, 1.0)"
TabUnfocused = "rgba(24, 24, 24, 1.0)"
TabUnfocusedActive = "rgba(49, 49, 49, 1.0)"
PlotLines = "rgba(119, 119, 119, 1.0)"
PlotLinesHovered = "rgba(255, 99, 0, 1.0)"
PlotHistogram = "rgba(149, 149, 149, 1.0)"
PlotHistogramHovered = "rgba(255, 99, 0, 1.0)"
TableHeaderBg = "rgba(48, 48, 51, 1.0)"
TableBorderStrong = "rgba(79, 79, 89, 1.0)"
TableBorderLight = "rgba(58, 58, 63, 1.0)"
TableRowBg = "rgba(0, 0, 0, 0.0)"
TableRowBgAlt = "rgba(255, 255, 255, 0.05999999865889549)"
TextSelectedBg = "rgba(255, 255, 255, 0.1560000032186508)"
DragDropTarget = "rgba(255, 99, 0, 1.0)"
NavHighlight = "rgba(255, 99, 0, 1.0)"
NavWindowingHighlight = "rgba(255, 99, 0, 1.0)"
NavWindowingDimBg = "rgba(0, 0, 0, 0.5860000252723694)"
ModalWindowDimBg = "rgba(0, 0, 0, 0.5860000252723694)"