# Windark style by DestroyerDarkNess from ImThemes
alpha = 1.0
disabledAlpha = 0.6000000238418579
windowPadding = [8.0, 8.0]
windowRounding = 8.399999618530273
windowBorderSize = 1.0
windowMinSize = [32.0, 32.0]
windowTitleAlign = [0.0, 0.5]
windowMenuButtonPosition = "Right"
childRounding = 3.0
childBorderSize = 1.0
popupRounding = 3.0
popupBorderSize = 1.0
framePadding = [4.0, 3.0]
frameRounding = 3.0
frameBorderSize = 1.0
itemSpacing = [8.0, 4.0]
itemInnerSpacing = [4.0, 4.0]
cellPadding = [4.0, 2.0]
indentSpacing = 21.0
columnsMinSpacing = 6.0
scrollbarSize = 5.599999904632568
scrollbarRounding = 18.0
grabMinSize = 10.0
grabRounding = 3.0
tabRounding = 3.0
tabBorderSize = 0.0
tabMinWidthForCloseButton = 0.0
colorButtonPosition = "Right"
buttonTextAlign = [0.5, 0.5]
selectableTextAlign = [0.0, 0.0]

[colors]
Text = "rgba(255, 255, 255, 1.0)"
TextDisabled = "rgba(153, 153, 153, 1.0)"
WindowBg = "rgba(32, 32, 32, 1.0)"
ChildBg = "rgba(32, 32, 32, 1.0)"
PopupBg = "rgba(43, 43, 43, 1.0)"
Border = "rgba(64, 64, 64, 1.0)"
BorderShadow = "rgba(0, 0, 0, 0.0)"
FrameBg = "rgba(43, 43, 43, 1.0)"
FrameBgHovered = "rgba(55, 55, 55, 1.0)"
FrameBgActive = "rgba(64, 64, 64, 1.0)"
TitleBg = "rgba(32, 32, 32, 1.0)"
TitleBgActive = "rgba(43, 43, 43, 1.0)"
TitleBgCollapsed = "rgba(32, 32, 32, 1.0)"
MenuBarBg = "rgba(43, 43, 43, 1.0)"
ScrollbarBg = "rgba(32, 32, 32, 1.0)"
ScrollbarGrab = "rgba(64, 64, 64, 1.0)"
ScrollbarGrabHovered = "rgba(77, 77, 77, 1.0)"
ScrollbarGrabActive = "rgba(89, 89, 89, 1.0)"
CheckMark = "rgba(0, 120, 215, 1.0)"
SliderGrab = "rgba(0, 120, 215, 1.0)"
SliderGrabActive = "rgba(0, 84, 153, 1.0)"
Button = "rgba(43, 43, 43, 1.0)"
ButtonHovered = "rgba(55, 55, 55, 1.0)"
ButtonActive = "rgba(64, 64, 64, 1.0)"
Header = "rgba(55, 55, 55, 1.0)"
HeaderHovered = "rgba(64, 64, 64, 1.0)"
HeaderActive = "rgba(77, 77, 77, 1.0)"
Separator = "rgba(55, 55, 55, 1.0)"
SeparatorHovered = "rgba(64, 64, 64, 1.0)"
SeparatorActive = "rgba(77, 77, 77, 1.0)"
ResizeGrip = "rgba(55, 55, 55, 1.0)"
ResizeGripHovered = "rgba(64, 64, 64, 1.0)"
ResizeGripActive = "rgba(77, 77, 77, 1.0)"
Tab = "rgba(43, 43, 43, 1.0)"
TabHovered = "rgba(55, 55, 55, 1.0)"
TabActive = "rgba(64, 64, 64, 1.0)"
TabUnfocused = "rgba(43, 43, 43, 1.0)"
TabUnfocusedActive = "rgba(55, 55, 55, 1.0)"
PlotLines = "rgba(0, 120, 215, 1.0)"
PlotLinesHovered = "rgba(0, 84, 153, 1.0)"
PlotHistogram = "rgba(0, 120, 215, 1.0)"
PlotHistogramHovered = "rgba(0, 84, 153, 1.0)"
TableHeaderBg = "rgba(48, 48, 51, 1.0)"
TableBorderStrong = "rgba(79, 79, 89, 1.0)"
TableBorderLight = "rgba(58, 58, 63, 1.0)"
TableRowBg = "rgba(0, 0, 0, 0.0)"
TableRowBgAlt = "rgba(255, 255, 255, 0.05999999865889549)"
TextSelectedBg = "rgba(0, 120, 215, 1.0)"
DragDropTarget = "rgba(255, 255, 0, 0.8999999761581421)"
NavHighlight = "rgba(66, 150, 249, 1.0)"
NavWindowingHighlight = "rgba(255, 255, 255, 0.699999988079071)"
NavWindowingDimBg = "rgba(204, 204, 204, 0.2000000029802322)"
ModalWindowDimBg = "rgba(204, 204, 204, 0.3499999940395355)"